# Form implementation generated from reading ui file 'QTDesign/Main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 208)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_LogIn = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_LogIn.setGeometry(QtCore.QRect(110, 40, 201, 16))
        self.lbl_LogIn.setObjectName("lbl_LogIn")
        self.btn_LogIn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_LogIn.setGeometry(QtCore.QRect(110, 60, 81, 31))
        self.btn_LogIn.setObjectName("btn_LogIn")
        self.lbl_Register = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_Register.setGeometry(QtCore.QRect(110, 100, 171, 16))
        self.lbl_Register.setObjectName("lbl_Register")
        self.btn_Register = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_Register.setGeometry(QtCore.QRect(110, 120, 81, 31))
        self.btn_Register.setObjectName("btn_Register")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_LogIn.setText(_translate("MainWindow", "¿Ya tienes cuenta? Inicia sesión"))
        self.btn_LogIn.setText(_translate("MainWindow", "Inicia Sesión"))
        self.lbl_Register.setText(_translate("MainWindow", "¿No tienes cuenta? cree una"))
        self.btn_Register.setText(_translate("MainWindow", "Registrarse"))
