# Form implementation generated from reading ui file 'QTDesign/window_Recipes.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_recipes(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_Recipes = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_Recipes.setGeometry(QtCore.QRect(60, 30, 101, 16))
        self.lbl_Recipes.setObjectName("lbl_Recipes")
        self.txt_Recipes = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_Recipes.setGeometry(QtCore.QRect(60, 60, 251, 31))
        self.txt_Recipes.setObjectName("txt_Recipes")
        self.btn_Recipes = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_Recipes.setGeometry(QtCore.QRect(330, 60, 81, 31))
        self.btn_Recipes.setObjectName("btn_Recipes")
        self.lst_Recipes = QtWidgets.QListView(parent=self.centralwidget)
        self.lst_Recipes.setGeometry(QtCore.QRect(60, 100, 671, 451))
        self.lst_Recipes.setObjectName("lst_Recipes")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_Recipes.setText(_translate("MainWindow", "TextLabel"))
        self.btn_Recipes.setText(_translate("MainWindow", "PushButton"))
