# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(629, 309)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(380, 160, 81, 31))
        self.btn_login.setObjectName("btn_login")
        self.txt_pwdLogin = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_pwdLogin.setGeometry(QtCore.QRect(260, 110, 201, 31))
        self.txt_pwdLogin.setObjectName("txt_pwdLogin")
        self.lbl_userLogin = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_userLogin.setGeometry(QtCore.QRect(140, 70, 101, 16))
        self.lbl_userLogin.setObjectName("lbl_userLogin")
        self.lbl_pwdLogin = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_pwdLogin.setGeometry(QtCore.QRect(140, 120, 71, 16))
        self.lbl_pwdLogin.setObjectName("lbl_pwdLogin")
        self.txt_userLogin = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_userLogin.setGeometry(QtCore.QRect(260, 60, 201, 31))
        self.txt_userLogin.setObjectName("txt_userLogin")
        self.lbl_login = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_login.setGeometry(QtCore.QRect(140, 20, 181, 16))
        self.lbl_login.setObjectName("lbl_login")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 629, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_login.setText(_translate("MainWindow", "Iniciar sesión"))
        self.lbl_userLogin.setText(_translate("MainWindow", "Nombre de usuario"))
        self.lbl_pwdLogin.setText(_translate("MainWindow", "Contraseña"))
        self.lbl_login.setText(_translate("MainWindow", "Bienvenido"))
